# /bin/sh                                                                                                                      
#----------------Parameters---------------------- #                                                                            
#$ -S /bin/sh                                                                                                                  
#$ -pe mthread 20                                                                                                              
#$ -q sThC.q                                                                                                                   
#$ -l mres=120G,h_data=6G,h_vmem=6G                                                                                            
#$ -cwd                                                                                                                        
#$ -j y                                                                                                                        
#$ -N blastdbcmd                                                                                                         
#$ -o logs/blastdbcmd.log                                                                                                
#$ -m bea                                                                                                                      
#                                                                                                                              
# ----------------Modules------------------------- #                                                                           
#                                                                                                                              
module load ~/modulefiles/miniconda                                                                                            
source activate blast_tools                                                                                                    
#                                                                                                                              
# ----------------Your Commands------------------- #                                                                           
#                                                                                                                              
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME                                                  
#                                                                                                                              
blastdbcmd -db /scratch/dbs/blast/v5/nt \                                                                                      
           -entry_batch results/coi_accession_list_2020_04_01.txt \                                                            
           -out results/coi_from_nt.fasta                                                                                      
#                                                                                                                              
echo = `date` job $JOB_NAME done       